### ISSUE TITLE
r-oldrel-macos-x86_64 CRAN tests failing

### ISSUE THREAD

**Issue by ablack3** [OHDSI/Andromeda#19]
It seems that one of the Andromeda tests fails on the r-oldrel-macos-x86_64 environment.

https://cran.rstudio.com//web/checks/check_results_Andromeda.html
![image](https://user-images.githubusercontent.com/10227522/117488465-715fcd80-af3a-11eb-85a7-23d5ddcd7688.png)

We get the last 13 lines of output which does not provide any help in identifying the cause of the error. 
![image](https://user-images.githubusercontent.com/10227522/117489153-475adb00-af3b-11eb-94df-13e02c786ce6.png)

I really need a way to reproduce the error and test a fix. The specs of the cran machine are:
![image](https://user-images.githubusercontent.com/10227522/117489642-dbc53d80-af3b-11eb-83de-12bf4e14fef6.png)

Mac OS: 10.11.6, XCode 8.2.1, clang 4.0.0, gfortran 6.1, R 3.6.3

`rversions::r_oldrel()` tells me that the old release R version is 3.6.3. I installed R 3.6.3 on my Mac mini running Mac OS 10.15 with xcode 12.4 and clang 12.0.0. All tests passed and R CMD check worked fine on this computer.

Unfortunately it looks like r-oldrel-macos is not one of the rhub options.
``` r
rhub::platforms()
#> debian-clang-devel:
#>   Debian Linux, R-devel, clang, ISO-8859-15 locale
#> debian-gcc-devel:
#>   Debian Linux, R-devel, GCC
#> debian-gcc-devel-nold:
#>   Debian Linux, R-devel, GCC, no long double
#> debian-gcc-patched:
#>   Debian Linux, R-patched, GCC
#> debian-gcc-release:
#>   Debian Linux, R-release, GCC
#> fedora-clang-devel:
#>   Fedora Linux, R-devel, clang, gfortran
#> fedora-gcc-devel:
#>   Fedora Linux, R-devel, GCC
#> linux-x86_64-centos-epel:
#>   CentOS 8, stock R from EPEL
#> linux-x86_64-rocker-gcc-san:
#>   Debian Linux, R-devel, GCC ASAN/UBSAN
#> macos-highsierra-release:
#>   macOS 10.13.6 High Sierra, R-release, brew
#> macos-highsierra-release-cran:
#>   macOS 10.13.6 High Sierra, R-release, CRAN's setup
#> solaris-x86-patched:
#>   Oracle Solaris 10, x86, 32 bit, R-release
#> solaris-x86-patched-ods:
#>   Oracle Solaris 10, x86, 32 bit, R-release, Oracle Developer Studio 12.6
#> ubuntu-gcc-devel:
#>   Ubuntu Linux 20.04.1 LTS, R-devel, GCC
#> ubuntu-gcc-release:
#>   Ubuntu Linux 20.04.1 LTS, R-release, GCC
#> ubuntu-rchk:
#>   Ubuntu Linux 20.04.1 LTS, R-devel with rchk
#> windows-x86_64-devel:
#>   Windows Server 2008 R2 SP1, R-devel, 32/64 bit
#> windows-x86_64-oldrel:
#>   Windows Server 2008 R2 SP1, R-oldrel, 32/64 bit
#> windows-x86_64-patched:
#>   Windows Server 2008 R2 SP1, R-patched, 32/64 bit
#> windows-x86_64-release:
#>   Windows Server 2008 R2 SP1, R-release, 32/64 bit
```

It looks to me like github actions does not support old version of mac OS: https://github.com/actions/virtual-environments/issues/461.

Maybe it is time to dig the 10 year old macbook out of the closet.

@msuchard, @schuemie Any ideas about what to try next?

**Comment by ablack3** [comment]
I successfully ran R CMD Check on a 2009 Macbook running Mac OS 10.11.6 with clang v8.0.0, gfortran v7.2.0, R 3.6.2.

**Comment by schuemie** [comment]
Are the folks at CRAN requiring us to fix the error? If not, we can always ignore it.

**Comment by ablack3** [comment]
Ignoring this since CRAN is not requiring a fix.
