### ISSUE TITLE
Relative `andromedaTempFile` causes write issue in some environments

### ISSUE THREAD

**Issue by msuchard** [OHDSI/Andromeda#2]
This `option(andromedaTempFile = "~/andromeda")` causes a write issue in (at least) one RstudioServer/linux environment, while `option(andromedaTempFile = "/home/user/andromeda")` works just fine.

Am not sure what the issue is, but posting here so that we do not forget the work-around.

**Comment by schuemie** [comment]
Maybe we could use [path.expand](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/path.expand) when reading the `andromedaTempFile` option?

**Comment by msuchard** [comment]
That's a great idea.  I'll check it out when I can coordinate access to this environment again.  Thanks!

**Comment by msuchard** [comment]
I can confirm that in this environment:

`path.expand("~/andromeda")` expands to `"/home/username/andromeda"`.  I'll make the patch.

**Comment by ablack3** [comment]
This is fixed as far as I know. Closing the issue.

``` r
library(Andromeda)
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

options(andromedaTempFile = "~/andromeda")

getOption("andromedaTempFile")
#> [1] "~/andromeda"

db <- andromeda()

db
#> # Andromeda object
#> # Physical location:  /var/folders/xx/01v98b6546ldnm1rg1_bvk000000gn/T//Rtmpv1z0DM/file11f8d42207d4b.sqlite
#> 
#> Tables:
```

<sup>Created on 2021-12-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
