### ISSUE TITLE
Vignette Not Found

### ISSUE THREAD

**Issue by jduke99** [OHDSI/Andromeda#20]
The [vignette](https://raw.githubusercontent.com/OHDSI/Andromeda/master/inst/doc/UsingAndromeda.pdf) on the Andromeda homepage throws a 404.

**Comment by ablack3** [comment]
Thanks for pointing this out. This has been fixed on the [develop branch](https://github.com/OHDSI/Andromeda/tree/develop) and will be updated in the main branch on the next release.
