### ISSUE TITLE
Create workaround for zip bug with large files

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Andromeda#21]
There's a [bug in the `zip` package](https://github.com/r-lib/zip/issues/65) that I don't think will ever be fixed. We should probable think about another solution that avoids this problem.

The bug is in the `zip_list()` function used [here](https://github.com/OHDSI/Andromeda/blob/bd8666b84faba407bcf24ca81e205431ebaf5e78/R/LoadingSaving.R#L124). Some options that come to mind:
- Drop zip altogether and instead use the zip library in Java. (as for example done in [DatabaseConnector](https://github.com/OHDSI/DatabaseConnector/blob/0ab0ddfa4299ffd4d0c66d84640a5fe4fb831efd/R/Compression.R#L31))
- Avoid the need to list the files in the zip file. Instead just unzip the files in a temp subfolder (of the temp folder), and rename them from there. Note that it is important to rename the files right after extracting, because it is possible the user opens the same Andromeda file twice (e.g. in different threads)

**Comment by schuemie** [comment]
Another option: 
- Use utils::unzip(zipFileName, list = TRUE) instead

**Comment by ablack3** [comment]
Sorry for the delay. I think `utils::unzip(zipFileName, list = TRUE)` is the simplest solution and I'll make the change in the development branch.

**Comment by ablack3** [comment]
This has been fixed on the develop branch and will be included in the next release. I don't have an automated test for this issue since we need a ~3GB Andromeda zip file but I have an ad-hoc manual test.

**Comment by ablack3** [comment]
Fixed in v0.5.0
