### ISSUE TITLE
arrow version: add isAndromedaTable()

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Andromeda#45]
In the new version, Andromeda tables can be of various R classes. It would be convenient to have an isAndromedaTable() function to check if a table is an Andromeda table.

Ideally this would be made available in a new version before the transition to Arrow.

**Comment by ablack3** [comment]
Implemented in the develop branch. I guess I should push the isAndromedaTable to main in a new release then prior to the switch to arrow.
